// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFgkgh-1wz972I0_anKF-r9OxXxLSPuuY',
    appId: '1:71020148677:web:1aa399b8ca07ce25187dac',
    messagingSenderId: '71020148677',
    projectId: 'ranked-e5df1',
    authDomain: 'ranked-e5df1.firebaseapp.com',
    storageBucket: 'ranked-e5df1.firebasestorage.app',
    measurementId: 'G-SBK2X62VYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk8ROpF_sC4lR19OYH3qOsq5DbsPEUNDw',
    appId: '1:71020148677:android:7909f30726be38b2187dac',
    messagingSenderId: '71020148677',
    projectId: 'ranked-e5df1',
    storageBucket: 'ranked-e5df1.firebasestorage.app',
  );

  // Windows uses the same configuration as web
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFgkgh-1wz972I0_anKF-r9OxXxLSPuuY',
    appId: '1:71020148677:web:1aa399b8ca07ce25187dac',
    messagingSenderId: '71020148677',
    projectId: 'ranked-e5df1',
    authDomain: 'ranked-e5df1.firebaseapp.com',
    storageBucket: 'ranked-e5df1.firebasestorage.app',
    measurementId: 'G-SBK2X62VYB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk8ROpF_sC4lR19OYH3qOsq5DbsPEUNDw',
    appId: '1:71020148677:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '71020148677',
    projectId: 'ranked-e5df1',
    iosBundleId: 'com.jukuio.ranked',
    storageBucket: 'ranked-e5df1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk8ROpF_sC4lR19OYH3qOsq5DbsPEUNDw',
    appId: '1:71020148677:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '71020148677',
    projectId: 'ranked-e5df1',
    iosBundleId: 'com.jukuio.ranked',
    storageBucket: 'ranked-e5df1.firebasestorage.app',
  );
}
